apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p4d3u8g9k-nodejs
  janus-idp.io/tekton: p4d3u8g9k-nodejs
  backstage.io/kubernetes-id: p4d3u8g9k-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p4d3u8g9k-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
