apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: p4d3u8g9k-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: p4d3u8g9k-nodejs 
  name: p4d3u8g9k-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: p4d3u8g9k-nodejs 
